FROM python:3.12-slim


WORKDIR /app


RUN pip install --no-cache-dir poetry


COPY pyproject.toml poetry.lock* /app/


RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi


COPY . /app


CMD ["celery", "-A", "src.celery_app.celery_app", "worker", "--loglevel=info"]
